name: 'Create an Organization Repository'
description: 'Creates an Organization Repository and adds the Actor as an admin'
inputs:
  repo-name:  # change this as needed
    description: 'What is the name of the repository?'
    required: true
    default: ''
  org-admin-token:
    description: 'Organization admin token with admin:org scope'
    required: true
    default: ''
  template-repo-name:
    description: "Template Repo to create repo from"
    required: true
    default: ''
  owner:
    description: "The organization or person who will own the new repository. To create a new repository in an organization, the authenticated user must be a member of the specified organization."
    required: false
    default: ''
  description:
    description: 'A short description of the new repository.'
    required: false
    default: ''
  include_all_branches:
    description: 'Set to true to include the directory structure and files from all branches in the template repository, and not just the default branch.'
    required: false
    default: false
  private:
    description: 'Either true to create a new private repository or false to create a new public one.'
    required: false
    default: false
outputs:
  repo-url: # change this as needed
    description: 'URL of the created repository'
runs:
  using: 'node12'
  main: 'dist/index.js'
